version: "3"

services:
  ### NGINX Service #######################################
  nginx:
    build:
      context: ./nginx
    healthcheck:
      test: "curl -f http://localhost/ping || exit 1"
      start_period: 5s
      retries: 2
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - appnet

  ### API Service #########################################
  api:
    build:
      context: ./api
      target: ${SERVER_ENV:-production}
    expose:
      - "3000"
    healthcheck:
      test: "php ./healthcheck.php"
      start_period: 5s
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - appnet

  ### Web Service #########################################
  web:
    build:
      context: ./web
      target: ${SERVER_ENV:-production}
    expose:
      - "8000"
    healthcheck:
      test: "node ./healthcheck.js"
      start_period: 30s
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - appnet

  ### MariaDB Service #####################################
  mariadb:
    image: mariadb:10.6
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin -psecret ping -h localhost
      start_period: 5s
    environment:
      - MARIADB_USER=lunarecords
      - MARIADB_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:

volumes:
  mariadb:
  redis:
