name: API CI

on:
  push:
    paths:
      - "api/**"
      - "!api/*.md"
      - ".github/workflows/api-ci.yml"
    branches:
      - "**"
    tags-ignore:
      - "**"

env:
  workdir: ./api

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-composer
        with:
          path: ${{ env.workdir }}/vendor
          key: composer-${{ hashFiles(format('{0}/composer.lock', env.workdir)) }}
      - if: steps.cache-composer.outputs.cache-hit != 'true'
        working-directory: ${{ env.workdir }}
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.workdir }}/vendor
          key: composer-${{ hashFiles(format('{0}/composer.lock', env.workdir)) }}
      - run: ./vendor/bin/php-cs-fixer fix --dry-run
        working-directory: ${{ env.workdir }}

  test:
    needs: setup
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: lunarecords
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.workdir }}/vendor
          key: composer-${{ hashFiles(format('{0}/composer.lock', env.workdir)) }}
      - run: |
          cp .env.example .env
          ./vendor/bin/phpunit
        working-directory: ${{ env.workdir }}
